name: tammybejano200@gmail.com 

{

 "private_key": "d38a75a1bade93728c8e68569979777f521108c3c0f357f021d70db232bd4017",

 "address": "34a35dfa41d07936",

 "email": "tammybejano200@gmail.com"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: default doc job cable storage ujs test db

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop --parallel
